twitter_analysis_tweepy:
  target: dev
  outputs:
    dev:
      dataset: idowu_dataset_tweepy
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: ./service_account.json
      location: europe-west4
      method: service-account
      priority: interactive
      project: idowupluralproj
      threads: 4
      type: bigquery
    
    prod:
      dataset: production_tweepy
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: ./service_account.json
      location: europe-west4
      method: service-account
      priority: interactive
      project: idowupluralproj
      threads: 4
      type: bigquery

  
